import React from "react";
import ReactDOM from "react-dom/client";
import App from "./App";
import "./styles.css";
import "./styles/sidebar.css";
import "./styles/env-panel.css";
import "./styles/terminal.css";
import "./styles/command-palette.css";
import "./styles/command-bookmarks.css";
import "./styles/terminal-themes.css";
import "./styles/task-runner.css";
import "./styles/task-graph.css";
import "./styles/app-theme-picker.css";
import "./styles/keyboard-shortcuts.css";
import "./styles/github-sidebar.css";
import "./styles/task-history.css";
import "./styles/theme-editor.css";
import "./styles/density-picker.css";
import "./styles/custom-css-editor.css";
import "./styles/stash-manager.css";
import "./styles/blame-view.css";
import "./styles/branch-compare.css";
import "./styles/git-hooks.css";
import "./styles/conflict-resolver.css";
import "./styles/security-audit.css";
import "./styles/secret-scanner.css";
import "./styles/license-report.css";
import "./styles/security-headers.css";
import "./styles/test-runner-panel.css";
import "./styles/coverage-report.css";
import "./styles/benchmark-dashboard.css";
import "./styles/docker-panel.css";
import "./styles/docker-images.css";
import "./styles/container-monitor.css";
import "./styles/flaky-tests.css";
import "./styles/notification-center.css";
import "./styles/activity-timeline.css";
import "./styles/plugin-manager.css";
import "./styles/backup-restore.css";
import "./styles/analytics-dashboard.css";
import "./styles/ai-chat.css";
import "./styles/unified-search.css";
import "./styles/settings-page.css";
import "./styles/terminal-recording.css";
import "./styles/dora-metrics.css";
import "./styles/webhook-events.css";
import "./styles/ssh-manager.css";
import "./styles/git-analytics.css";
import "./styles/snippet-manager.css";
import "./styles/env-diff.css";
import "./styles/app-performance.css";
import "./styles/file-explorer.css";
import "./styles/quick-actions.css";
import "./styles/project-overview.css";
import "./styles/inline-diff.css";
import "./styles/web-vitals.css";
import "./styles/plugin-runtime.css";
import "./styles/dependency-analyzer.css";
import "./styles/port-scanner.css";
import "./styles/directory-stats.css";
import "./styles/tag-manager.css";
import "./styles/git-log.css";
import "./styles/workspace-manager.css";
import "./styles/task-scheduler.css";
import "./styles/clipboard-history.css";
import "./styles/todo-panel.css";
import "./styles/quick-switcher.css";
import "./styles/error-diagnosis.css";
import "./styles/browser-events.css";
import "./styles/database-explorer.css";
import "./styles/dashboard.css";
import "./styles/status-bar.css";

ReactDOM.createRoot(document.getElementById("root") as HTMLElement).render(
  <React.StrictMode>
    <App />
  </React.StrictMode>,
);
